// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmandel_engine.h"

extern XMandel_engine_Config XMandel_engine_ConfigTable[];

XMandel_engine_Config *XMandel_engine_LookupConfig(u16 DeviceId) {
	XMandel_engine_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMANDEL_ENGINE_NUM_INSTANCES; Index++) {
		if (XMandel_engine_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMandel_engine_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMandel_engine_Initialize(XMandel_engine *InstancePtr, u16 DeviceId) {
	XMandel_engine_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMandel_engine_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMandel_engine_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

