// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XMANDEL_ENGINE_H
#define XMANDEL_ENGINE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmandel_engine_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XMandel_engine_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XMandel_engine;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMandel_engine_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMandel_engine_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMandel_engine_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMandel_engine_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMandel_engine_Initialize(XMandel_engine *InstancePtr, u16 DeviceId);
XMandel_engine_Config* XMandel_engine_LookupConfig(u16 DeviceId);
int XMandel_engine_CfgInitialize(XMandel_engine *InstancePtr, XMandel_engine_Config *ConfigPtr);
#else
int XMandel_engine_Initialize(XMandel_engine *InstancePtr, const char* InstanceName);
int XMandel_engine_Release(XMandel_engine *InstancePtr);
#endif

void XMandel_engine_Start(XMandel_engine *InstancePtr);
u32 XMandel_engine_IsDone(XMandel_engine *InstancePtr);
u32 XMandel_engine_IsIdle(XMandel_engine *InstancePtr);
u32 XMandel_engine_IsReady(XMandel_engine *InstancePtr);
void XMandel_engine_EnableAutoRestart(XMandel_engine *InstancePtr);
void XMandel_engine_DisableAutoRestart(XMandel_engine *InstancePtr);
u32 XMandel_engine_Get_return(XMandel_engine *InstancePtr);

void XMandel_engine_Set_pr(XMandel_engine *InstancePtr, u32 Data);
u32 XMandel_engine_Get_pr(XMandel_engine *InstancePtr);
void XMandel_engine_Set_pi(XMandel_engine *InstancePtr, u32 Data);
u32 XMandel_engine_Get_pi(XMandel_engine *InstancePtr);

void XMandel_engine_InterruptGlobalEnable(XMandel_engine *InstancePtr);
void XMandel_engine_InterruptGlobalDisable(XMandel_engine *InstancePtr);
void XMandel_engine_InterruptEnable(XMandel_engine *InstancePtr, u32 Mask);
void XMandel_engine_InterruptDisable(XMandel_engine *InstancePtr, u32 Mask);
void XMandel_engine_InterruptClear(XMandel_engine *InstancePtr, u32 Mask);
u32 XMandel_engine_InterruptGetEnabled(XMandel_engine *InstancePtr);
u32 XMandel_engine_InterruptGetStatus(XMandel_engine *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
