// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmandel_engine.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMandel_engine_CfgInitialize(XMandel_engine *InstancePtr, XMandel_engine_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMandel_engine_Start(XMandel_engine *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMandel_engine_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_AP_CTRL) & 0x80;
    XMandel_engine_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMandel_engine_IsDone(XMandel_engine *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMandel_engine_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMandel_engine_IsIdle(XMandel_engine *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMandel_engine_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMandel_engine_IsReady(XMandel_engine *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMandel_engine_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMandel_engine_EnableAutoRestart(XMandel_engine *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMandel_engine_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XMandel_engine_DisableAutoRestart(XMandel_engine *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMandel_engine_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XMandel_engine_Get_return(XMandel_engine *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMandel_engine_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_AP_RETURN);
    return Data;
}
void XMandel_engine_Set_pr(XMandel_engine *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMandel_engine_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_PR_DATA, Data);
}

u32 XMandel_engine_Get_pr(XMandel_engine *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMandel_engine_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_PR_DATA);
    return Data;
}

void XMandel_engine_Set_pi(XMandel_engine *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMandel_engine_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_PI_DATA, Data);
}

u32 XMandel_engine_Get_pi(XMandel_engine *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMandel_engine_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_PI_DATA);
    return Data;
}

void XMandel_engine_InterruptGlobalEnable(XMandel_engine *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMandel_engine_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_GIE, 1);
}

void XMandel_engine_InterruptGlobalDisable(XMandel_engine *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMandel_engine_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_GIE, 0);
}

void XMandel_engine_InterruptEnable(XMandel_engine *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMandel_engine_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_IER);
    XMandel_engine_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_IER, Register | Mask);
}

void XMandel_engine_InterruptDisable(XMandel_engine *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMandel_engine_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_IER);
    XMandel_engine_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_IER, Register & (~Mask));
}

void XMandel_engine_InterruptClear(XMandel_engine *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMandel_engine_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_ISR, Mask);
}

u32 XMandel_engine_InterruptGetEnabled(XMandel_engine *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMandel_engine_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_IER);
}

u32 XMandel_engine_InterruptGetStatus(XMandel_engine *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMandel_engine_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDEL_ENGINE_AXILITES_ADDR_ISR);
}

